### ISSUE TITLE
How to select only classes and not instances ?

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikibase#34]
Interesting comment on Twitter : https://twitter.com/ewg118/status/982756470864465921

**Comment by wetneb** [comment]
Wikidata's structure does not make it very easy as there is no clear-cut distinction between instances and classes: it is possible for some concept to be an instance of something and a subclass of something else.

One thing that was suggested to me would be to automatically add a special type ("class") to all items that have a "subclass of" (P279) statement. In this way you could reconcile only against this special type. I think that would work pretty well but that would not let you filter these classes to a particular domain.

**Comment by ettorerizza** [comment]
> One thing that was suggested to me would be to automatically add a special type ("class") to all items that have a "subclass of" (P279) statement.

I don't know the Wikidata API very well, but I suppose there is no way to filter the entities for which a property exists or does not exist? (eg : "skyphos" NOT EXISTS P31 | EXIST P279)

**Comment by wetneb** [comment]
This is definitely doable in SPARQL, but that would be too expensive an API call for the reconciliation endpoint. But even with performance aside, the main question for me is how do we expose that to the user.

**Comment by wetneb** [comment]
Hmm… I'm not sure: this would not make it possible to reconcile to particular subclasses of a given class. Also, ideally I would prefer not to mess up too much with the existing reconciliation API.

**Comment by ettorerizza** [comment]
You may be right, I admit I have not thought much about it. My intuition was just : now that we can enrich the data matched with Wikidata, it can be useful to filter _a priori_ those who have the properties that interests us (population, geographical location ...), which will avoid useless API call. In other words, "match these names with Wikidata only if I can then get this or that property". 

This would also allow a finer reconciliation. We can not always rely on P31 and P279 in Wikidata, they are too often misused. But as a general rule of thumb, a human must have at least one "given name" (P735)

**Comment by wetneb** [comment]
Yes, totally - for instance, people have very uninformative types (Q5) so it would be better if we could use "occupation" or "position held" in some cases… For cases like these, I think we could try to revive Freebase's "query-based reconciliation", or take some inspiration from the SPARQL-based reconciliation services of the RDF extension… The standard reconciliation service API is useful for its simplicity and efficiency, but there is no hope to make it general enough to handle all cases.

**Comment by thadguidry** [comment]
Its not only do-able, but you can even get a sense of what's the most
populated classes in Wikidata :)  But yes there's a query cost, but luckily
subclass of P279 and instance of P31 are indexed on the backend so it's not
that costly.

By the way, you can change P279 in the query to any other property that
your interested in.

https://query.wikidata.org/sparql?query=SELECT%20%3Fclass%20(COUNT(%3Fsubject)%20AS%20%3FcountSubject)%20WHERE%20%7B%0A%20%20%7B%20SELECT%20DISTINCT%20%3Fsubject%20%3Fclass%0A%20%20%20%20WHERE%20%7B%0A%20%20%20%20%20%20%3Fsubject%20wdt%3AP279%20%3Fobject%20.%0A%20%20%20%20%20%20%3Fsubject%20wdt%3AP31%20%3Fclass%0A%20%20%20%20%7D%20%7D%0A%20%20%20%0A%7D%20GROUP%20BY%20%3Fclass%20ORDER%20BY%20DESC(%3FcountSubject)

What will forever suck about Wikidata is that it doesn't have Types and
instead Types are derived by multiple Statements, it makes things much
harder than putting things into boxes by applying Types like Freebase did
and then filling in those Types with Statements.  Instead, with Wikidata
you have to "build your boxes" with multiple Statements and then query
against topics that have those Statements applied to them.  The indexing
needed is compounded to the total number of Statements.

-Thad

**Comment by ettorerizza** [comment]
@thadguidry Weird that Q5 doesn't appear in the first results of your sparql query : http://tinyurl.com/yajxhnzc

What's wrong with it ?

**Comment by thadguidry** [comment]
@ettorerizza well it is because it does not ask the question your trying to ask...because it depends on what your really trying to ask.  My hunch is that your asking for "populated classes", in other words, classes/types in Wikidata that actually have recommended properties that could be filled in ?

That would be this query:
https://query.wikidata.org/#SELECT%20DISTINCT%20%3Fitem%20%3FitemLabel%20%3Fproperties_for_this_type%20%3Fproperties_for_this_typeLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fitem%20wdt%3AP1963%20%3Fproperties_for_this_type.%20%7D%0A%7D%20ORDER%20BY%20%3Fitem%0A

This is a shortened listing of all subclasses of a class... again potentially anything can be placed in a bucket type (a bucket type is a type that may or may not have any corresponding populated properties) ...
https://query.wikidata.org/#SELECT%20%3Fsubclass%20%3FsubclassLabel%20%3Fclass%20%3FclassLabel%20WHERE%20%7B%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%20%20OPTIONAL%20%7B%20%3Fsubclass%20wdt%3AP279%20%3Fclass.%20%7D%0A%7D%0ALIMIT%20100

**Comment by wetneb** [comment]
There is no simple way to tell those things apart in Wikidata's modelling so let's close this.
