### ISSUE TITLE
Impossible to match these five QIDs

### ISSUE THREAD

**Issue by ettorerizza** [wetneb/openrefine-wikibase#43]
I don't know what these five QIDs have in particular, but I cannot match them with Wikidata (they exist, they are even very important items, and "search for match" finds them). 

Weird. It may be nothing, but it may be the sign of a bug somewhere, so I prefer to report it.

To reproduce the bug : go on column "qid", try to reconcile with Wikidata (en) by choosing "Reconcile against no particular type".

![screencast](https://user-images.githubusercontent.com/6286410/45932500-425cdf00-bf7d-11e8-9a1f-616a73f7cf6b.gif)

(OR 2.8 and 3.0, Windows 10, Google Chrome)

**OR Project :** [wikipedia_errors.openrefine.tar.gz](https://github.com/wetneb/openrefine-wikibase/files/2409082/wikipedia_errors.openrefine.tar.gz)

**Comment by wetneb** [comment]
Yes they are excluded because they are instances of a subclass of https://www.wikidata.org/wiki/Q17442446. As the description indicates, instances of this item "should not refer to external World entities", so we don't match them. This exclusion policy is useful to get rid of items about wikimedia templates, categories, duplicated items, and so on.

I think some "subclass of" statement needs to be removed so that "order metaclass" is no longer a subclass of this.

That being said, maybe that filtering does not make sense when Qids are provided directly.

**Comment by ettorerizza** [comment]
Arf. The Wikidata's ontology is a mess. Among these metaclasses, we find concepts as common as "ship", "profession", "textile fiber", "shoe style" or ... "race from The Legend of Zelda" (which can, therefore, be reconciled in OR only if we select the type "Wikidata metaclass")

**Comment by antoine2711** [comment]
@ettorerizza : why don't you use the function « Use values as identifiers » with the column « Qid » instead of trying to reconcile it?

**Comment by wetneb** [comment]
So that's not a bug with the recon service, it is working as intended here.
