### ISSUE TITLE
Scrollkeeping and pagekeeping after manual reconciliation

### ISSUE THREAD

**Issue by tholbach** [wetneb/openrefine-wikibase#64]
Currently I'm being redirected to the first page of my selected results whenever I search manually for a match after the reconciliation process with Wikidata. If you happen to run into a reconciliation result which does not cover a lot of your entries, this can be quite tiring. 

**Steps to reproduce**
* do a reconciliation against wikidata
* go to one of the following pages of the result
* click on "Search for match" to find a result manually
* choose it and apply it
* -> you're redirected to the first page

![scrollkeeping](https://user-images.githubusercontent.com/16371850/63929436-b4715a00-ca51-11e9-913b-a9ca37652b0e.gif)

It was ease the work if the page was not redirecting and I could continue cross-checking the results! 
Thank you!

**Comment by wetneb** [comment]
Yes this is a known issue: https://github.com/OpenRefine/OpenRefine/issues/33
The workaround is to use the reconciliation judgment facet to restrict to unmatched cells.

Closing this as this belongs to the OpenRefine repository (not because I am satisfied by the workaround!). Feel free to report issues in either repository though (I can triage them).

**Comment by tholbach** [comment]
I thought it might belong here as it's a result of the wikidata reconcilation! Thanks for pointing to it!

**Comment by wetneb** [comment]
Indeed! But sadly this problem happens for all reconciliation services, not just the one for Wikidata :)
