### ISSUE TITLE
Reconcile labels against all available languages of a Wikibase item?

### ISSUE THREAD

**Issue by regisrob** [wetneb/openrefine-wikibase#67]
Hello,

Context: I have my own Wikibase and WDQS instances in production, and I want to set up a reconciliation service on top of it, so that users can perform matchings with my Wikibase entities from their OpenRefine. The reconciliation service works fine, I can reconcile strings in OpenRefine against the data stored in my Wikibase instance... 

Issue : But there is a noteworthy difference compared to the Wikidata reconciliation service (which is based on this tool if I am not wrong): 
- with Wikidata, i.e. by using the web service URL with the "en" language prefix (https://tools.wmflabs.org/openrefine-wikidata/en/api), I am able to find matches among labels in any other language of a given Wikidata item. For instance, if I send a request for "Jacopo de Fazio", which is an alias in French and Italian for [Q313460](https://www.wikidata.org/wiki/Q313460), OpenRefine will match Q313460 as expected, even if I'm using the "en" language code in the web service url. 
- Whereas in my own instance, i.e. by using my own reconciliation service, it can only perform matching of labels in the same language: e.g. if I use "https://my-service.org/openrefine-wikidata/en/api", the web service only searches for labels in English in my Wikibase. This means that I am forced to launch the reconciliation process in OpenRefine for every single language, one by one :(

I do not know how the Wikidata reconciliation service is able to take into account all the aliases in all the language of a given Wikidata item. The data is modeled in the same way in Wikidata and in my Wikibase, and I do not see any difference between the two in the way the RDF data is structured into the respective triplestores... 

Is it possible to enable the same behaviour as the Wikidata reconciliation service? (i.e. to look for labels in every languages in one API call)

Thanks for your help!

**Comment by wetneb** [comment]
Hi @regisrob,

Thanks for reaching out! This is a curious issue.

The reconciliation endpoint for Wikidata does use this code base and I have not made any custom changes for Wikidata. So I suspect the behaviour you are observing must come from differences in the configuration of Wikibase's own search engine. This should be simple to check:
- go to your Wikibase instance, and set your language to the language you use in the reconciliation service;
- search for your query at Special:Search (the equivalent of https://www.wikidata.org/wiki/Special:Search) and see if the item shows up
- search for your query in the search box in the top right corner, without pressing Enter (just looking at the suggestions that appear as you type) and see if the item shows up

If your item shows up in any of these search scenarios (Special:Search and in the search suggestions) then it really should also show up in the reconciliation service (because the reconciliation service calls both APIs and merges the results). This means that there is a problem in the `openrefine-wikibase` code and we should investigate further.

If your item does not show up in any of these search methods, then that means the problem comes from Wikibase: you should tweak Wikibase's search configuration to fix the problem. (I am not sure how though… but hopefully it gets you on the right track)

**Comment by regisrob** [comment]
Thank you @wetneb for your quick and extensive answer. I have also asked the question on the Wikidata-tech list: https://lists.wikimedia.org/pipermail/wikidata-tech/2019-September/001452.html. 

You were right, the problem actually comes from the Wikibase's search configuration... Wikidata is using the WikibaseCirrusSearch extension, and we don't. As I was saying in my answer on wikidata-tech, the suggestion box does not perform cross-languages search in our instance: the autocomplete mechanism is only aware of the current active language. But on the other hand the main Wikibase search (via Special:Search) does seem to search all available languages... 
So, based on what you said above, I wonder if there is not an issue in openrefine-wikibase still (even if the best way to benefit from a proper cross-languages search, both within Wikibase and from the reconciliation service, would be to use CirrusSearch, as Wikidata does). 
What do you think?

**Comment by wetneb** [comment]
If the item you are looking for shows up in search results but not in the reconciliation results then yes, there might be something to solve for us here.

If your instance is public, could you share its location? And an example of item where the problem shows up?

Otherwise, if it is not publicly available, I would try inspecting the results of the API requests made by the reconciliation endpoint. You can find them here:
https://github.com/wetneb/openrefine-wikibase/blob/47aeaa517b43782ab175ca4f4c7a3b6963f8afed/wdreconcile/engine.py#L33-L59

**Comment by regisrob** [comment]
Yes it is publicly available here: https://data.biblissima.fr 
For instance, if you search for [Jakob von Viraggio](https://data.biblissima.fr/w/index.php?search=Jakob+von+Viraggio&title=Sp%C3%A9cial%3ARecherche&profile=default&fulltext=1) (German alias for Q8075), the Mediawiki search engine will get you Q8075 whatever your current language is. But the autocomplete box only suggests you Q8075 if you have selected the Deutsch language.

**Comment by wetneb** [comment]
Interesting! There seems to be a discrepancy between what is returned by the UI:
https://data.biblissima.fr/w/index.php?search=Jakob+von+Viraggio&title=Sp%C3%A9cial%3ARecherche&profile=default&fulltext=1
and what is returned by the API:
https://data.biblissima.fr/w/api.php?action=query&list=search&srnamespace=0&srsearch=Jakob%20von%20Viraggio

This API endpoint is the one that corresponds to Special:Search, so in theory both result lists should match.

I am not familiar enough with Wikibase to understand what is going on here. But as far as reconciliation is concerned, this bug should be solved by tweaking Wikibase to make the API and Special:Search return the same thing. Using CirrusSearch could be a solution, although I would expect it should be possible to do without.

**Comment by regisrob** [comment]
I understand the problem from the reconciliation service standpoint, and I don't know enough about wikibase either to solve the issue... I would be happy to find a workaround without having to switch to CirrusSearch right now. I will ask for further details on a wikidata/wikibase channel. Thank you very much for your help ;)

**Comment by wetneb** [comment]
Ok! Let's leave this open even if it seems like the bug comes from Wikibase - once you find a solution to the issue i think it would be worth documenting it in this repo so that others could follow suit.

**Comment by regisrob** [comment]
I had this answer from Lucas Werkmeister:

> The API version was missing srnamespace=120 (only searches main namespace by default, not Item namespace) and srwhat=text (no idea what the default here is tbh). This version works: https://data.biblissima.fr/w/api.php?action=query&list=search&srsearch=Jakob%20von%20Viraggio&srnamespace=120&srwhat=text

... which makes a lot a sense.

So I guess there may be a tiny fix to be made to the `wikidata_string_search` function. What do you think? I could give a try as soon as possible and let you know.

**Comment by wetneb** [comment]
Yes we just need to make the namespace configurable and add the srwhat option! Do you want to make a PR for that? Let me know if you need any help for that.

**Comment by regisrob** [comment]
Sure, at least I can try! I'll take some time to test it out and then make a PR. I let you know if I need help 😉. Thanks

**Comment by regisrob** [comment]
I've pushed a first stab at solving this issue in the above PR.

It seems to work fine, but it certainly needs review and tests!

It was a little bit tricky to find the pieces of code that were really specific to Wikidata (i.e. the fact that Wikidata uses the Main Mediawiki namespace, and not the default Wikibase namespace "120")

**Comment by wetneb** [comment]
Thanks a lot! Yes I will comment there.
