### ISSUE TITLE
Custom matching heuristics for specific languages

### ISSUE THREAD

**Issue by wetneb** [wetneb/openrefine-wikibase#71]
It was requested at https://github.com/OpenRefine/OpenRefine/issues/2267 to refine the matching heuristics to equate `ij` and `y` for Dutch names.

First, this requires having full control over the indexing profile, since it is not enough to change our own scoring mechanism for this. Running our own index is something I want to do on the long term, but it requires a lot more resources and maintenance work than running a wrapper on top of Wikidata's APIs.

Then, I wonder if it is feasible to have language-specific analyzers (which means storing labels and aliases in language-specific fields), and letting users specify the language which should be used for the queries (for instance depending on their language setting in the reconciliation endpoint). We probably want to also have a language-agnostic matching mode, for datasets where languages are mixed (and as a sensible default).

Or, could we have a generic phonetic index (which would identify "ij" and "i", "ss" and "ß", and other things like that)? This is likely to be biased towards western languages and could potentially generate a lot of false positives.

**Comment by thadguidry** [comment]
For Digraphs (parts of a word are considered equivalent if written with alternative glyph or letters)...

I feel like it would be better to do this on the client side, and letting the user assume a bit of work for the language they are working in, otherwise you end up with recon services having to add support for phonetic indexes and perhaps only Wikidata would have the resources to do that.

Ways that a user could assume a bit of work:
1. Generating a new column in OpenRefine to store alternatives.

name | alternative
------|--------
Arie Luijendijk | Arie Luyendyk 
Dirk Kuijt | Dirk Kuyt
Ruud van Nistelrooij | Ruud van Nistelrrooy

2. The new column could be created by some library that knows about digraphs in a particular language, perhaps like [Frog](https://languagemachines.github.io/frog/) or NLTK

3. Communities could improve the libraries out there (like Frog) that then helps the entire world of language processing in a shared fashion among many tools, and not just OpenRefine or Wikidata.

**Comment by tfmorris** [comment]
Using Unicode normalization forms NFC or NFKC would probably help the vast majority of the cases, including the esset ß. It would also take care of the ĳ ligature vs ij, but it would not handle equivalence with ÿ or the degenerate y form.

The ICU4J library's `com.ibm.icu.text.Normalizer2` can handle this. At a higher level than this, you'd need to get language specific, which means either identifying, or being told the language. Something similar to [ScandinavianNormalizationFilterFactory](http://www.solr-start.com/javadoc/solr-lucene/org/apache/lucene/analysis/miscellaneous/ScandinavianNormalizationFilterFactory.html) "This filter normalize use of the interchangeable Scandinavian characters æÆäÄöÖøØ and folded variants (aa, ao, ae, oe and oo) by transforming them to åÅæÆøØ."

This is also just basic search functionality though. It seems like the right place to implemented it would be in Wikibase/Wikidata, so it would improve the general search capabilities there.

**Comment by wetneb** [comment]
makes sense, so let's mark this as out of scope for this repo.
