### ISSUE TITLE
Problem with accented characters

### ISSUE THREAD

**Issue by anchardo** [wetneb/openrefine-wikibase#82]
Hello,
As indicated in a previous issue (https://github.com/wetneb/openrefine-wikibase/issues/81), I'm testing this reconciliation service by connecting it to an independent Wikibase instance.
So, I don't know if this is a problem related to my particular instance/API or more general, but the reconciliation service doesn't seem to work correctly if candidate words contain any accents. 

Example: the service remains in "working" mode (more than 15 minutes) with the candidate "Andr**é**e de Jongh". With "Andr**e**e de Jongh", it doesn't retrieve my Wikibase element "Andrée de Jongh" _(not the same fuzzy matching algorithm as used by the "classic" Wikidata/OpenRefine service?)_, but it isn't blocked as with "Andrée de Jongh".

I hope this is the right place to report this, if this isn't the case, don't hesitate to delete this issue!

**Comment by wetneb** [comment]
This could be due to various things. OpenRefine is not very good at reporting errors raised by reconciliation services, so you could try querying the reconciliation service yourself. You can use the reconciliation test bench for this:
https://reconciliation-api.github.io/testbench/
Go to the Test bench tab, add the URL of your reconciliation service (which can be local), and then try sending "Andrée de Jongh". This will give you a direct link to the results, which you can open in your browser and see what sort of JSON response you get back (an error, perhaps?).

I suspect the discrepancy between Wikidata and your Wikibase could be due to the way search is configured on your instance. To get the same search behaviour you should use the CirrusSearch extension to use ElasticSearch and its full range of features, rather than the default SQL search.

There might also be a way to adapt the reconciliation service when your wikibase uses SQL search (perhaps that implies a different behaviour in the MediaWiki, but I would not expect so).

**Comment by anchardo** [comment]
When trying "Andrée de Jongh" on the testbench, I still get an error.
`Error: JSONP request to http://localhost:8000/fr/api?queries=%7B%22q0%22%3A%7B%22query%22%3A%22Andr%C3%A9e+de+Jongh%22%7D%7D failed`
I haven't yet paid much attention to CirrusSearch (maybe I should! ;)). I see it in the extensions list on my 'special:Version' page, but I'm not sure if it's currently used. 

In any case thanks for your help, but I must admit at this point this isn't my priority to have something perfectly operational, I mostly wanted to experiment if it's possible to have a working reconciliation service associated to a Wikibase and... I have my answer :)
