### ISSUE TITLE
Stale data (6 months old) being returned

### ISSUE THREAD

**Issue by tfmorris** [wetneb/openrefine-wikibase#91]
Reconciling "Black Girl" against Wikidata (en) for the type Film returned two candidates with scores of 100, which were clearly duplicates, including this one:

![Screen Shot 2020-10-04 at 6 43 50 PM](https://user-images.githubusercontent.com/82178/95030069-e30d2b80-067a-11eb-8f12-ac59bd6b4a96.png)

but when I went to merge the duplicate, I found that it had already been [merged](https://www.wikidata.org/w/index.php?title=Q70778234&action=history) in March 2020. It would be much more useful if the service returned only current data.

Service URL was https://wdreconcile.toolforge.org/en/api

**Comment by wetneb** [comment]
That is interesting!
This seems to be an issue in Wikidata itself: if I [search for "Black Girl"](https://www.wikidata.org/w/index.php?search=Black+Girl&search=Black+Girl&title=Special%3ASearch&go=Go&ns0=1&ns120=1), I get both Q3211102 and Q70778234 in the first page of results. The latter should probably not be there indeed, since it has been redirected.

So I created this Phabricator ticket: https://phabricator.wikimedia.org/T264566
