### ISSUE TITLE
improve Suggest Property

### ISSUE THREAD

**Issue by VladimirAlexiev** [wetneb/openrefine-wikibase#93]
https://reconciliation-api.github.io/testbench/ > test bench> Suggest > Property:
I'm looking for "MIC market code (P7534) ISO 10383 market identifier code".
These searches don't find it:
- mic iso
- mic code
- iso market

Please:
- collect all labels and descriptions (you already do)
- put them in a bag of words
- search the query words against that bag, in any order, not as substring

FTS engines like Elastic do that. What are you using to index labels and descriptions?

**Comment by wetneb** [comment]
Hi @VladimirAlexiev,

For the property suggest service, we just call directly Wikidata's own service, the API action `wbsearchentities`:
https://www.wikidata.org/w/api.php?action=help&modules=wbsearchentities
This gives you the same results as what you would have when adding a claim on an item in Wikidata.

You are correct that this is quite restrictive (it's only prefix search in SQL I think). But I think it would make sense to suggest these improvements to Wikidata directly, since it would then benefit a much bigger user base.

You could perhaps fill a phabricator ticket here:
https://phabricator.wikimedia.org/maniphest/task/edit/form/1/

**Comment by VladimirAlexiev** [comment]
(It's substring not prefix). Will post to phabricator.

https://www.wikidata.org/w/index.php?search=Property%3Aiso+mic&ns0=1&ns120=1 returns what I need, can you use that?

**Comment by wetneb** [comment]
The problem with this API endpoint is that it is likely to miss results in other cases. For instance, if you use it for items (not properties), [searching for "United States of America"](https://www.wikidata.org/w/index.php?search=United+States+of+America&search=United+States+of+America&title=Special%3ASearch&go=Go&ns0=1&ns120=1) will not return [Q30](https://www.wikidata.org/wiki/Q30) in its first page of results.
Perhaps that happens less with properties (since there are less properties anyway) but it would be a bit curious to use one endpoint to suggest properties and another one for items.

Generally speaking, since the intended use case of the suggest API is the same as the auto-complete Wikidata API, I think it makes sense to rely on the same mechanism, so that people get a uniform behaviour.

**Comment by VladimirAlexiev** [comment]
posted https://phabricator.wikimedia.org/T266212

**Comment by wetneb** [comment]
closing per the above
